apiVersion: v1
kind: Service
metadata:
  name: class-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: class-project
---
apiVersion: v1
kind: Secret
metadata:
  name: dbconfig
type: Opaque
stringData:
  dbconfig.json: '{"login": "dbuser", "pass": "admin123", "address": "mysql-svc", "dbname": "classdb"}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class-project
  template:
    metadata:
      labels:
        app: class-project
    spec:
      containers:
      - name: class-project
        image: iluhins/classproject:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
          - name: dbconfig-vol
            mountPath: "/etc/app"
            readOnly: true
      volumes:
        - name: project-persistent-storage
          persistentVolumeClaim:
            claimName: csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage


  
